name: test2
on: [pull_request]
jobs:
  html_preview:
    runs-on: ubuntu-latest
    name: HTML Preview
    steps:
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
      shellcommand: "asciidoctor README.adoc"
   - name: Get HTML preview link
     id: html_preview
     uses: shikharvashistha/html-preview-action@v3
     with:
     html_file: README.html
   - uses: mb2dev/github-action-comment-pull-request@1.0.0
     with:
       steps.html_preview.outputs.url: https://htmlpreview.github.io/?https://github.com/shikharvashistha/ublas/blob/gh-pages/README.html
       message: ${{ format('[Click here to preview HTML page in browser]({0})', steps.html_preview.outputs.url) }}
       GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
