name: test2
on: [pull_request]
jobs:
  asciidoc:
    runs-on: ubuntu-latest
    name: asciidoc
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: 2.7
    - uses: reitzig/actions-asciidoctor@v2.0.0
      with:
          version: 2.0.10
    - run: asciidoctor --version
