name: test
on:
  push:
    branches: [ docs ]
jobs:
  html_preview:
    runs-on: ubuntu-latest
    name: HTML Preview
    steps:
      - uses: actions/checkout@v2
      - name: Get HTML preview link
        id: html_preview
        uses: pavi2410/html-preview-action@v2
      - uses: actions/github-script@v3
        with:
          #message: ${{ format('[Click here to preview HTML page in browser]({0})', steps.html_preview.outputs.url) }}
          github-token: ${{ secrets.SECRET_TOKEN }}
          script: |
            github.issues.createComment({              
              body: ${{ format('[Click here to preview HTML page in browser]({0})', steps.html_preview.outputs.url) }}
            })
