name: test2
on: [pull_request]
jobs:
  html_preview:
    runs-on: ubuntu-latest
    name: HTML Preview
    steps:
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
      shellcommand: "asciidoctor README.adoc"
